apiVersion: apps/v1
kind: Deployment
metadata:
  name: lookup-deployment
  labels:
    app.kubernetes.io/name: lookup
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: lookup
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lookup
    spec:
      containers:
        - name: lookup
          image: "{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          resources: {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: VITE_ENV
              valueFrom:
                secretKeyRef:
                  name: lookup-env-secret
                  key: VITE_ENV
      restartPolicy: Always